---
- name: Initial setup
  hosts: webservers
  gather_facts: no
  remote_user: root

  roles:
    - swap
    - packages
    - user
    - add_key_to_user

- name: Install env for rails
  hosts: webservers
  gather_facts: no
  remote_user: "{{ user }}"

  roles:
    - rvm
    - postgres
    - nginx_config
