---
- name: Install necessary packages
  apt: 
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: 
    - ['curl', 'git-core', 'postgresql', 'postgresql-contrib', 'libpq-dev',
        'nodejs']
