---
- name: Import GPG keys
  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

- name: Install rvm installer
  get_url:
    url: https://get.rvm.io
    dest: /tmp/rvm-installer.sh
    mode: 0755
  
- name: Install rvm
  command: /tmp/rvm-installer.sh stable
